with Ada.Streams;
with DDS_Support.Sequences_Generic.Write_JSON_Generic;
package DDS.JSON_Out is
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Standard.String);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DDS.BuiltinTopicKey_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DDS.String);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DDS.EntityNameQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Natural);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Octet);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Octet_Seq.Sequence);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : UserDataQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DDS.Boolean);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Property_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Property_T_Seq.Sequence);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : PropertyQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : VendorId_Array_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : VendorId_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DomainId_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : EncapsulationId_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Transport_ClassId_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Unsigned_Long);
   procedure Write is new EncapsulationId_Seq.Write_JSON_Generic (Write, Write);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Locator_Address_Array_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : GUID_T_Value_Array);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Guid_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Duration_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Locator_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : OwnershipQosPolicyKind);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : OwnershipQosPolicy);
   procedure Write is new DDS.String_Seq.Write_JSON_Generic (Write, Write);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : PartitionQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : OwnershipStrengthQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : TransportInfo_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DestinationOrderQosPolicyKind);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DestinationOrderQosPolicyScopeKind);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : TopicDataQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : Tags_T);
   procedure Write is new DDS.Tags_Seq.Write_JSON_Generic (Write, Write);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DataTagQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : PresentationQosPolicyAccessScopeKind);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DestinationOrderQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : PresentationQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DurabilityQosPolicyKind);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : ServiceQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DurabilityQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : LivelinessQosPolicyKind);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : LivelinessQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DeadlineQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : LatencyBudgetQosPolicy);
   procedure Write is new DDS.Locator_Seq.Write_JSON_Generic (Write, Write);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DataRepresentationId_T);
   procedure Write is new DDS.DataRepresentationId_Seq.Write_JSON_Generic (Write, Write);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : CompressionSettings_T);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DataRepresentationQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : ParticipantTrustAttributesMask);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : PluginParticipantTrustAttributesMask);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : ParticipantTrustInfo);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : TrustInterceptorMask);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : TrustSignatureMask);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : TrustSignatureBit);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : ParticipantTrustSignatureAlgorithms);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : ParticipantTrustInterceptorAlgorithms);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : TrustKeyEstablishmentMask);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : GroupDataQosPolicy);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : TrustKeyEstablishmentBit);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : ParticipantTrustKeyEstablishmentAlgorithms);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : ParticipantTrustAlgorithms);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : ContentFilterProperty_T);
   procedure Write is new DDS.TransportInfo_Seq.Write_JSON_Generic (Write, Write);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DDS.ParticipantBuiltinTopicData);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DDS.PublicationBuiltinTopicData);
   procedure Write (To : not null access Ada.Streams.Root_Stream_Type'Class; Item : DDS.SubscriptionBuiltinTopicData);

end DDS.JSON_Out;
